language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: GR3ZRCiXCNozA7qeqI0RORt0ro5F5c0Z0JEldhSu7/NfdTkINQd3bcEl0ObwWYZXeFoFQp8QdOqFjmOut+FRA7xMXeJtg/sDB4p+626/ALWgOWxbRwGFSQ1MylLB3ruh8Cn3yu/41H6lKYVPPrhgIXIIgndx9WlAkWBESBXgo9PHvsZzSNETsTOoh3X4KGc4kigzsLUGaenOovXGpVjHMwstr2lTYvCQkMh4LAie7Ms+KN90r1wu/H98vJ/CJMi9WIhdM20TeFqmWwE25xEh4IJcNrEtKWvCy5ynW8ZBCr+RXR7pjEVG6ttd6zHAhYcTQHGkjCLeEffkbVZrHpqY71Mg4BMgW1pZuAuNbzCiize1FDPEEg6xBXra/yHKsTvetALoLs2dDfS0mmExA+g77WaKRbQiEuN46UJc8X6pbJfe83wNoUhljz75SdogcqlGZ1DQCYCjqnp4wRiBqTpwWpFn3fWGekgvUTC1U44nuZrNLJu4DLgyheuZ7kaDfQym8jvoKPs0UcWd7mH32Guj8vPdlN3Nx1XuHaJox78Uv+MTa5cyweEHjeYXhb1I1iFY2rjzNtpTQfE/XAUFLpWwN+oIYXI3md8BkAGs2o60Yz+Zql1hMISzOtGzcrstKXp4dASZihZ4kuyNMagpIKBPfmjX9T5nq3w/ePupaHkEEvE=
